apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    apps: mysql
spec:
  selector:
    matchLabels:
      apps: mysql
  replicas: 1
  template:
    metadata:
      labels:
        apps: mysql
    spec:
      containers:
        -  name: mysql
           image: mysql:8.0
           volumeMounts:
            - mountPath: "var/lib/mysql"
              name: data-volume
           ports:
            - containerPort: 3306
           envFrom:
            - secretRef:
               name: db-secret
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: pvc-storage-class
              
          
