apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        -  name: mysql
           image: mysql:8.0
           args:
            - "--default-authentication-plugin=mysql_native_password"
           volumeMounts:
            - mountPath: "var/lib/mysql"
              name: data-volume
           ports:
            - containerPort: 3306
              name: mysql
           envFrom:
            - configMapRef:
               name: db-config
            - secretRef:
               name: db-secret
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: pvc-storage-class
              
          
