apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-storage-class
spec:
  storageClassName: gcp-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
